import os
import cv2
import torch
import torch.nn as nn
import torchvision.ops.roi_align as roi_align
import numpy as np

from lib.backbones import dla
from lib.backbones.dlaup import DLAUp
from lib.helpers.decode_helper import extract_input_from_tensor
from experiments.config import cfg


class CenterNet3D(nn.Module):
    def __init__(self, backbone='dla34', neck='DLAUp', num_class=3, downsample=4, modality=None, IN_pretrained=True):
        """
        CenterNet for monocular 3D object detection.
        :param backbone: the backbone of pipeline, such as dla34.
        :param neck: the necks of detection, such as dla_up.
        :param downsample: the ratio of down sample. [4, 8, 16, 32]
        :param head_conv: the channels of convolution in head. default: 256
        """
        assert downsample in [4, 8, 16, 32]
        super().__init__()

        self.modality = modality

        if cfg['model']['depth&uncer_dcp']:
            self.heads = {'heatmap': num_class, 'offset_2d': 2, 'size_2d' :2, 'depth': 1, 'depth_uncer': 1, 'offset_3d': 2, 'size_3d':3, 'heading': 24}
        else:
            self.heads = {'heatmap': num_class, 'offset_2d': 2, 'size_2d' :2, 'depth': 2, 'offset_3d': 2, 'size_3d':3, 'heading': 24}
        
        input_channels = 3
        if IN_pretrained:
            self.backbone = getattr(dla, backbone)(pretrained=True, return_levels=True, input_channels=input_channels)
        else:
            self.backbone = getattr(dla, backbone)(pretrained=False, return_levels=True, input_channels=input_channels)        
        channels = self.backbone.channels  # channels list for feature maps generated by backbone
        self.first_level = int(np.log2(downsample))
        scales = [2 ** i for i in range(len(channels[self.first_level:]))]
        self.neck = DLAUp(channels[self.first_level:], scales_list=scales)   # feature fusion [such as DLAup, FPN]

        # initialize the head of pipeline, according to heads setting.
        for head in self.heads.keys():
            output_channels = self.heads[head]
            fc = nn.Sequential(
                nn.Conv2d(channels[self.first_level], cfg['model']['feat_channel'], kernel_size=3, padding=1, bias=True),
                nn.ReLU(inplace=True),
                nn.Conv2d(cfg['model']['feat_channel'], output_channels, kernel_size=1, stride=1, padding=0, bias=True))

            # initialization
            if 'heatmap' in head:
                fc[-1].bias.data.fill_(-2.19)
            else:
                self.fill_fc_weights(fc)

            self.__setattr__(head, fc)



    def forward(self, inputs, targets, mode):
        if cfg['model']['type'] in ['centernet3d@rgb']:
            inputs = inputs['rgb']
        
        feat = self.backbone(inputs)
        feat = self.neck(feat[self.first_level:])

        if mode in ['val', 'test']:
            ret = {}
            for head in self.heads:
                ret[head] = self.__getattr__(head)(feat)
            if cfg['model']['depth&uncer_dcp']:
                ret['depth'] = torch.cat([ret['depth'], ret['depth_uncer']], dim=1)
            return ret

        BATCH_SIZE,_,HEIGHT,WIDE = feat.size()
        device = feat.device

        ret = {}
        contrastive_items = {}

        center2d_idx, cls_ids = targets['indices'], targets['cls_ids']    
        mask = targets['mask_2d'].to(torch.bool)                              
        num_objs = mask.sum()

        for head in self.heads:
            ret[head] = self.__getattr__(head)(feat)

        if cfg['model']['depth&uncer_dcp']:
            ret['depth'] = torch.cat([ret['depth'], ret['depth_uncer']], dim=1)

        return ret


    def fill_fc_weights(self, layers):
        for m in layers.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.normal_(m.weight, std=0.001)
                if m.bias is not None:
                    nn.init.constant_(m.bias, 0)


